### ISSUE TITLE
jwk errors when sending "Authorization: Bearer xxx" header

### ISSUE THREAD

**Issue by marcvs** [pysnippet/fastapi-oauth2#24]
### Bug description

Hi There,

I was trying to also provide a rest interface within the same `FastAPI()` app.

There, I noted that whenever I send any kind of Bearer token (random string, valid jwt) to any endpoint, I get an error from `jose.jwt`.

The error depends on whether I send
- random string
- valid jwt
- valid jwt with correctly configuret jwt algorithm.

I guess, for now the random string is the real bug that should not occur, so I send that trace.

What' I'd love to have is an endpoint on which I could do my own checking, and `fastapi_oauth2` would not interfere, since I'm using my own lib (`flaat`) for that.

### server
```
@router_api.get("/test")
@flaat.is_authenticated()
def test(request: Request):
    logger.debug("eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
    response = JSONResponse({"key": "value"})
    return response
```

### client
```
http localhost:8000/api/v1/test "Authorization: Bearer `oidc-token egi`"
```

### Logs

```bash
Traceback (most recent call last):
  File "/home/marcus/.local/lib/python3.11/site-packages/jose/jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcus/.local/lib/python3.11/site-packages/jose/jwt.py", line 144, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/.local/lib/python3.11/site-packages/jose/jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "/home/marcus/.local/lib/python3.11/site-packages/jose/jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcus/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/.local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/marcus/.local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/marcus/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/marcus/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/marcus/.local/lib/python3.11/site-packages/fastapi_oauth2/middleware.py", line 145, in __call__
    await self.auth_middleware(scope, receive, send)
  File "/home/marcus/.local/lib/python3.11/site-packages/starlette/middleware/authentication.py", line 36, in __call__
    auth_result = await self.backend.authenticate(conn)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/.local/lib/python3.11/site-packages/fastapi_oauth2/middleware.py", line 107, in authenticate
    user = User(Auth.jwt_decode(param))
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/.local/lib/python3.11/site-packages/fastapi_oauth2/middleware.py", line 48, in jwt_decode
    return jwt_decode(token, cls.secret, algorithms=[cls.algorithm])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus/.local/lib/python3.11/site-packages/jose/jwt.py", line 146, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
```

**Comment by marcvs** [comment]
It can be reproduced on the master branch:
1. Start the daemon
```
cd examples/demonstrator
uvicorn main:app --reload
```
2. Run a request (using `httpie`, a neat `curl` replacement.
```
http http://localhost:8000/endpoint-non-existent "Authorization: Bearer x"
```

**Comment by ArtyomVancyan** [comment]
I see what the problem is. If you are using the `examples/demonstration` as a template, then please remove the `JWT_SECRET` value in the `.env` file or replace it with the secret that your JWT is signed with. If you look at `config.py`, it reads those configs from the environment variables: `jwt_secret=os.getenv("JWT_SECRET")`.

Alternatively, you can change nothing and sign your token using the `Auth.jwt_encode` method:

> [!NOTE]
> This works only within the runtime application that uses the properly configured middleware. E.g. The `examples/demonstration` is that kind of application.

```python
from fastapi_oauth2.middleware import Auth
Auth.jwt_encode({"message": "Thanks for using your OSS."})
```

Also, you can sign your token with the `"secret"` secret that is set as the default secret in the `.env` file, and that token will also work:

```python
from jose.jwt import encode as jwt_encode
jwt_encode({"message": "Thanks for using your OSS."}, "secret", "HS256")
```

Then, start the application and test:

```bash
http http://localhost:8000/ "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXNzYWdlIjoiVGhhbmtzIGZvciB1c2luZyB5b3VyIE9TUy4ifQ.EtclfQnp1z6j_po_AkhQle46NjvKiEUCgdGySflRk-k"
```

If you have any related or other questions, you are always welcome. Just for this kind of issue, I would prefer you to open a discussion then we will convert it to an issue if it will be necessary.

**Comment by marcvs** [comment]
I'm not sure this is addressing the issue. I've configured as you said, and I get a different error, related to jwt crypto.

My point was more about the fact, that I get anything different from "404" at all:
```
# works as expected:
http http://localhost:8000/endpoint-non-existent "Authorization: Bear"

HTTP/1.1 404 Not Found

# works not as expected:
http http://localhost:8000/endpoint-non-existent "Authorization: Bearer x"

HTTP/1.1 500 Internal Server Error
```
(This was for the issue section, I'll open the other point in the
discussion section.)

**Comment by ArtyomVancyan** [comment]
If the `Authorization` header is set, then middleware first checks the validity of its value and then proceeds to the endpoint. In your case, both `Authorization: Bear` and `Authorization: Bearer x` are invalid, and it causes some errors that are not handled, so it returns a 500 status code. If you did not pass the `Authorization` header or it was with a valid value, you would get a 404 status code.

```bash
http http://localhost:8000/endpoint-non-existent "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXNzYWdlIjoiVGhhbmtzIGZvciB1c2luZyB5b3VyIE9TUy4ifQ.EtclfQnp1z6j_po_AkhQle46NjvKiEUCgdGySflRk-k"
HTTP/1.1 404 Not Found
content-length: 22
content-type: application/json
date: Wed, 27 Sep 2023 12:13:46 GMT
server: uvicorn

{
    "detail": "Not Found"
}
```

**Comment by marcvs** [comment]
Right that works for me now, and I understand that better now.

One thing that puzzles me here is that I need to define the algorithm on the global scale (i.e. for all OAuthClients), but I'm not sure I understand this well enough :)
